<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<ol class="breadcrumb bc-3">
	<li>
		<a href="<?php echo base_url(); ?>dashboard"><i class="fas fa-home"></i>Home</a>
	</li>
	<li class="active">
		<strong>Alteração de Notas</strong>
	</li>
</ol>

<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<div class="row titulo-pagina">
	<div class="col-md-8">
		<h2>
			<h2>Alteração de Notas</h2>
		</h2>
	</div>
</div>

<div class="row"> 
	<div class="col-md-12"> 
		<form role="form" id="form1" method="post" action="<?php echo base_url();?>alteracao_notas/buscar_nota_nao_entregue" class="validate">
			<div class="panel panel-default panel-custom-form" data-collapsed="0"> 
				<div class="panel-heading">
					<div class="panel-title"><span class="text-danger"></span></div>
				</div>
				<div class="panel-body"> 
					<div class="row"> 
						<div class="col-md-6 form-group">
							<label class="control-label">Número da Nota</label>
							<input type="text" class="form-control form-uppercase" name="form-chave" id="form-chave" data-validate="required" data-message-required="Este campo é obrigatório." />
                            <?php echo form_error('form-chave');?>
						</div>
						<div class="col-md-6 form-group">
							<label class="control-label">Tempo Parametrizado</label>
							<input type="text" value="<?php echo $tempo[0]->param_nf_nao_recebidas; ?> Dias" class="form-control form-uppercase" readonly/>                            
						</div>
					</div>
				</div>
				<div class="panel-footer"> 
					<button type="submit" class="btn btn-info"><i class="fas fa-search"></i> Buscar</button>
				</div>
			</div>
		</form>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel-body panel-datatable">
			<table id="table-export-filter" class="table table-bordered table-striped datatable" style="width: 100%;">
				<thead>
					<tr>
						<th>Data</th>
						<th>Nota Fiscal</th>
						<th>Origem</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
					<?php
					if (isset($grid_dados) && $grid_dados) {
						foreach ($grid_dados as $dados) :
							$data_emissao	= date('d/m/Y', strtotime($dados->data_emissao));
							$hora_emissao	= $dados->hora_emissao;
							$numero_nota	= $dados->nota_fiscal;
							$emitente		= $dados->emitente;
							$id_nota		= $dados->id_nota;
							$pro_controlado = '';


							// Link Conferência Controlados
							$link_conferencia = "<a onclick='enviarFormulario($numero_nota,$id_nota)' class='btn btn-info btn-sm'>Marcar como Entregue</a>";						
					?>
							<tr>
								<td><?php echo $data_emissao; ?></td>
								<td><?php echo $numero_nota; ?></td>
								<td><?php echo $emitente; ?></td>
								<td>
									<?php echo $link_conferencia; ?>
								</td>
							</tr>

					<?php
						endforeach;
					}
					?>
				</tbody>
				<tfoot>
					<tr>
						<th>Data</th>
						<th>Nota Fiscal</th>
						<th>Origem</th>
						<th>Ação</th>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
<script>


	$(document).ready(function(){
		$('[data-toggle="tooltip"]').tooltip();
	});

	function enviarFormulario(numero_nota,id_nota) {

		swal({
			title: "Deseja realmente alterar o status dessa nota para Entregue?",
			type: "warning",
			showCancelButton: true,
			confirmButtonClass: 'btn-success',
			confirmButtonText: 'Sim',
			cancelButtonText: "Não",
			cancelButtonClass: "btn-danger",
			closeOnConfirm: false,
			closeOnCancel: false
		}, function(isConfirm) {
			
			if (isConfirm) {

				// Get the URL generated by the PHP code snippet
				var url = '<?php echo base_url() ?>alteracao_notas/maracar_como_entregue/'+numero_nota+'_'+id_nota;

				// Perform the redirect
				window.location.href = url;
				
				swal.close(); //fecha o popup
				
			} else {
				swal.close(); //fecha o popup				
			}
		});
	}

	const form = document.getElementById('form1');
	
	form.addEventListener("submit", (e) => {
		e.preventDefault();

		var formChave = document.getElementById("form-chave").value;
		if(formChave === '') return;

		form.submit();
		return;
		// handle submit
	});
</script>